export default[
[1, 'America/Adak', '-10:00', 'Hawaii-Aleutian Standard Time'],
[2, 'America/Atka', '-10:00', 'Hawaii-Aleutian Standard Time'],
[3, 'America/Anchorage', '-9:00', 'Alaska Standard Time'],
[4, 'America/Juneau', '-9:00', 'Alaska Standard Time'],
[5, 'America/Nome', '-9:00', 'Alaska Standard Time'],
[6, 'America/Yakutat', '-9:00', 'Alaska Standard Time'],
[7, 'America/Dawson', '-8:00', 'Pacific Standard Time'],
[8, 'America/Ensenada', '-8:00', 'Pacific Standard Time'],
[9, 'America/Los_Angeles', '-8:00', 'Pacific Standard Time'],
[10, 'America/Tijuana', '-8:00', 'Pacific Standard Time'],
[11, 'America/Vancouver', '-8:00', 'Pacific Standard Time'],
[12, 'America/Whitehorse', '-8:00', 'Pacific Standard Time'],
[13, 'Canada/Pacific', '-8:00', 'Pacific Standard Time'],
[14, 'Canada/Yukon', '-8:00', 'Pacific Standard Time'],
[15, 'Mexico/BajaNorte', '-8:00', 'Pacific Standard Time'],
[16, 'America/Boise', '-7:00', 'Mountain Standard Time'],
[17, 'America/Cambridge_Bay', '-7:00', 'Mountain Standard Time'],
[18, 'America/Chihuahua', '-7:00', 'Mountain Standard Time'],
[19, 'America/Dawson_Creek', '-7:00', 'Mountain Standard Time'],
[20, 'America/Denver', '-7:00', 'Mountain Standard Time'],
[21, 'America/Edmonton', '-7:00', 'Mountain Standard Time'],
[22, 'America/Hermosillo', '-7:00', 'Mountain Standard Time'],
[23, 'America/Inuvik', '-7:00', 'Mountain Standard Time'],
[24, 'America/Mazatlan', '-7:00', 'Mountain Standard Time'],
[25, 'America/Phoenix', '-7:00', 'Mountain Standard Time'],
[26, 'America/Shiprock', '-7:00', 'Mountain Standard Time'],
[27, 'America/Yellowknife', '-7:00', 'Mountain Standard Time'],
[28, 'Canada/Mountain', '-7:00', 'Mountain Standard Time'],
[29, 'Mexico/BajaSur', '-7:00', 'Mountain Standard Time'],
[30, 'America/Belize', '-6:00', 'Central Standard Time'],
[31, 'America/Cancun', '-6:00', 'Central Standard Time'],
[32, 'America/Chicago', '-6:00', 'Central Standard Time'],
[33, 'America/Costa_Rica', '-6:00', 'Central Standard Time'],
[34, 'America/El_Salvador', '-6:00', 'Central Standard Time'],
[35, 'America/Guatemala', '-6:00', 'Central Standard Time'],
[36, 'America/Knox_IN', '-6:00', 'Central Standard Time'],
[37, 'America/Managua', '-6:00', 'Central Standard Time'],
[38, 'America/Menominee', '-6:00', 'Central Standard Time'],
[39, 'America/Merida', '-6:00', 'Central Standard Time'],
[40, 'America/Mexico_City', '-6:00', 'Central Standard Time'],
[41, 'America/Monterrey', '-6:00', 'Central Standard Time'],
[42, 'America/Rainy_River', '-6:00', 'Central Standard Time'],
[43, 'America/Rankin_Inlet', '-6:00', 'Central Standard Time'],
[44, 'America/Regina', '-6:00', 'Central Standard Time'],
[45, 'America/Swift_Current', '-6:00', 'Central Standard Time'],
[46, 'America/Tegucigalpa', '-6:00', 'Central Standard Time'],
[47, 'America/Winnipeg', '-6:00', 'Central Standard Time'],
[48, 'Canada/Central', '-6:00', 'Central Standard Time'],
[49, 'Canada/East-Saskatchewan', '-6:00', 'Central Standard Time'],
[50, 'Canada/Saskatchewan', '-6:00', 'Central Standard Time'],
[51, 'Chile/EasterIsland', '-6:00', 'Easter Is. Time'],
[52, 'Mexico/General', '-6:00', 'Central Standard Time'],
[53, 'America/Atikokan', '-5:00', 'Eastern Standard Time'],
[54, 'America/Bogota', '-5:00', 'Colombia Time'],
[55, 'America/Cayman', '-5:00', 'Eastern Standard Time'],
[56, 'America/Coral_Harbour', '-5:00', 'Eastern Standard Time'],
[57, 'America/Detroit', '-5:00', 'Eastern Standard Time'],
[58, 'America/Fort_Wayne', '-5:00', 'Eastern Standard Time'],
[59, 'America/Grand_Turk', '-5:00', 'Eastern Standard Time'],
[60, 'America/Guayaquil', '-5:00', 'Ecuador Time'],
[61, 'America/Havana', '-5:00', 'Cuba Standard Time'],
[62, 'America/Indianapolis', '-5:00', 'Eastern Standard Time'],
[63, 'America/Iqaluit', '-5:00', 'Eastern Standard Time'],
[64, 'America/Jamaica', '-5:00', 'Eastern Standard Time'],
[65, 'America/Lima', '-5:00', 'Peru Time'],
[66, 'America/Louisville', '-5:00', 'Eastern Standard Time'],
[67, 'America/Montreal', '-5:00', 'Eastern Standard Time'],
[68, 'America/Nassau', '-5:00', 'Eastern Standard Time'],
[69, 'America/New_York', '-5:00', 'Eastern Standard Time'],
[70, 'America/Nipigon', '-5:00', 'Eastern Standard Time'],
[71, 'America/Panama', '-5:00', 'Eastern Standard Time'],
[72, 'America/Pangnirtung', '-5:00', 'Eastern Standard Time'],
[73, 'America/Port-au-Prince', '-5:00', 'Eastern Standard Time'],
[74, 'America/Resolute', '-5:00', 'Eastern Standard Time'],
[75, 'America/Thunder_Bay', '-5:00', 'Eastern Standard Time'],
[76, 'America/Toronto', '-5:00', 'Eastern Standard Time'],
[77, 'Canada/Eastern', '-5:00', 'Eastern Standard Time'],
[78, 'America/Caracas', '-4:30', 'Venezuela Time'],
[79, 'America/Anguilla', '-4:00', 'Atlantic Standard Time'],
[80, 'America/Antigua', '-4:00', 'Atlantic Standard Time'],
[81, 'America/Aruba', '-4:00', 'Atlantic Standard Time'],
[82, 'America/Asuncion', '-4:00', 'Paraguay Time'],
[83, 'America/Barbados', '-4:00', 'Atlantic Standard Time'],
[84, 'America/Blanc-Sablon', '-4:00', 'Atlantic Standard Time'],
[85, 'America/Boa_Vista', '-4:00', 'Amazon Time'],
[86, 'America/Campo_Grande', '-4:00', 'Amazon Time'],
[87, 'America/Cuiaba', '-4:00', 'Amazon Time'],
[88, 'America/Curacao', '-4:00', 'Atlantic Standard Time'],
[89, 'America/Dominica', '-4:00', 'Atlantic Standard Time'],
[90, 'America/Eirunepe', '-4:00', 'Amazon Time'],
[91, 'America/Glace_Bay', '-4:00', 'Atlantic Standard Time'],
[92, 'America/Goose_Bay', '-4:00', 'Atlantic Standard Time'],
[93, 'America/Grenada', '-4:00', 'Atlantic Standard Time'],
[94, 'America/Guadeloupe', '-4:00', 'Atlantic Standard Time'],
[95, 'America/Guyana', '-4:00', 'Guyana Time'],
[96, 'America/Halifax', '-4:00', 'Atlantic Standard Time'],
[97, 'America/La_Paz', '-4:00', 'Bolivia Time'],
[98, 'America/Manaus', '-4:00', 'Amazon Time'],
[99, 'America/Marigot', '-4:00', 'Atlantic Standard Time'],
[100, 'America/Martinique', '-4:00', 'Atlantic Standard Time'],
[101, 'America/Moncton', '-4:00', 'Atlantic Standard Time'],
[102, 'America/Montserrat', '-4:00', 'Atlantic Standard Time'],
[103, 'America/Port_of_Spain', '-4:00', 'Atlantic Standard Time'],
[104, 'America/Porto_Acre', '-4:00', 'Amazon Time'],
[105, 'America/Porto_Velho', '-4:00', 'Amazon Time'],
[106, 'America/Puerto_Rico', '-4:00', 'Atlantic Standard Time'],
[107, 'America/Rio_Branco', '-4:00', 'Amazon Time'],
[108, 'America/Santiago', '-4:00', 'Chile Time'],
[109, 'America/Santo_Domingo', '-4:00', 'Atlantic Standard Time'],
[110, 'America/St_Barthelemy', '-4:00', 'Atlantic Standard Time'],
[111, 'America/St_Kitts', '-4:00', 'Atlantic Standard Time'],
[112, 'America/St_Lucia', '-4:00', 'Atlantic Standard Time'],
[113, 'America/St_Thomas', '-4:00', 'Atlantic Standard Time'],
[114, 'America/St_Vincent', '-4:00', 'Atlantic Standard Time'],
[115, 'America/Thule', '-4:00', 'Atlantic Standard Time'],
[116, 'America/Tortola', '-4:00', 'Atlantic Standard Time'],
[117, 'America/Virgin', '-4:00', 'Atlantic Standard Time'],
[118, 'Antarctica/Palmer', '-4:00', 'Chile Time'],
[119, 'Atlantic/Bermuda', '-4:00', 'Atlantic Standard Time'],
[120, 'Atlantic/Stanley', '-4:00', 'Falkland Is. Time'],
[121, 'Brazil/Acre', '-4:00', 'Amazon Time'],
[122, 'Brazil/West', '-4:00', 'Amazon Time'],
[123, 'Canada/Atlantic', '-4:00', 'Atlantic Standard Time'],
[124, 'Chile/Continental', '-4:00', 'Chile Time'],
[125, 'America/St_Johns', '-3:30', 'Newfoundland Standard Time'],
[126, 'Canada/Newfoundland', '-3:30', 'Newfoundland Standard Time'],
[127, 'America/Araguaina', '-3:00', 'Brasilia Time'],
[128, 'America/Bahia', '-3:00', 'Brasilia Time'],
[129, 'America/Belem', '-3:00', 'Brasilia Time'],
[130, 'America/Buenos_Aires', '-3:00', 'Argentine Time'],
[131, 'America/Catamarca', '-3:00', 'Argentine Time'],
[132, 'America/Cayenne', '-3:00', 'French Guiana Time'],
[133, 'America/Cordoba', '-3:00', 'Argentine Time'],
[134, 'America/Fortaleza', '-3:00', 'Brasilia Time'],
[135, 'America/Godthab', '-3:00', 'Western Greenland Time'],
[136, 'America/Jujuy', '-3:00', 'Argentine Time'],
[137, 'America/Maceio', '-3:00', 'Brasilia Time'],
[138, 'America/Mendoza', '-3:00', 'Argentine Time'],
[139, 'America/Miquelon', '-3:00', 'Pierre & Miquelon Standard Time'],
[140, 'America/Montevideo', '-3:00', 'Uruguay Time'],
[141, 'America/Paramaribo', '-3:00', 'Suriname Time'],
[142, 'America/Recife', '-3:00', 'Brasilia Time'],
[143, 'America/Rosario', '-3:00', 'Argentine Time'],
[144, 'America/Santarem', '-3:00', 'Brasilia Time'],
[145, 'America/Sao_Paulo', '-3:00', 'Brasilia Time'],
[146, 'Antarctica/Rothera', '-3:00', 'Rothera Time'],
[147, 'Brazil/East', '-3:00', 'Brasilia Time'],
[148, 'America/Noronha', '-2:00', 'Fernando de Noronha Time'],
[149, 'Atlantic/South_Georgia', '-2:00', 'South Georgia Standard Time'],
[150, 'Brazil/DeNoronha', '-2:00', 'Fernando de Noronha Time'],
[151, 'America/Scoresbysund', '-1:00', 'Eastern Greenland Time'],
[152, 'Atlantic/Azores', '-1:00', 'Azores Time'],
[153, 'Atlantic/Cape_Verde', '-1:00', 'Cape Verde Time'],
[154, 'Africa/Abidjan', '+0:00', 'Greenwich Mean Time'],
[155, 'Africa/Accra', '+0:00', 'Ghana Mean Time'],
[156, 'Africa/Bamako', '+0:00', 'Greenwich Mean Time'],
[157, 'Africa/Banjul', '+0:00', 'Greenwich Mean Time'],
[158, 'Africa/Bissau', '+0:00', 'Greenwich Mean Time'],
[159, 'Africa/Casablanca', '+0:00', 'Western European Time'],
[160, 'Africa/Conakry', '+0:00', 'Greenwich Mean Time'],
[161, 'Africa/Dakar', '+0:00', 'Greenwich Mean Time'],
[162, 'Africa/El_Aaiun', '+0:00', 'Western European Time'],
[163, 'Africa/Freetown', '+0:00', 'Greenwich Mean Time'],
[164, 'Africa/Lome', '+0:00', 'Greenwich Mean Time'],
[165, 'Africa/Monrovia', '+0:00', 'Greenwich Mean Time'],
[166, 'Africa/Nouakchott', '+0:00', 'Greenwich Mean Time'],
[167, 'Africa/Ouagadougou', '+0:00', 'Greenwich Mean Time'],
[168, 'Africa/Sao_Tome', '+0:00', 'Greenwich Mean Time'],
[169, 'Africa/Timbuktu', '+0:00', 'Greenwich Mean Time'],
[170, 'America/Danmarkshavn', '+0:00', 'Greenwich Mean Time'],
[171, 'Atlantic/Canary', '+0:00', 'Western European Time'],
[172, 'Atlantic/Faeroe', '+0:00', 'Western European Time'],
[173, 'Atlantic/Faroe', '+0:00', 'Western European Time'],
[174, 'Atlantic/Madeira', '+0:00', 'Western European Time'],
[175, 'Atlantic/Reykjavik', '+0:00', 'Greenwich Mean Time'],
[176, 'Atlantic/St_Helena', '+0:00', 'Greenwich Mean Time'],
[177, 'Europe/Belfast', '+0:00', 'Greenwich Mean Time'],
[178, 'Europe/Dublin', '+0:00', 'Greenwich Mean Time'],
[179, 'Europe/Guernsey', '+0:00', 'Greenwich Mean Time'],
[180, 'Europe/Isle_of_Man', '+0:00', 'Greenwich Mean Time'],
[181, 'Europe/Jersey', '+0:00', 'Greenwich Mean Time'],
[182, 'Europe/Lisbon', '+0:00', 'Western European Time'],
[183, 'Europe/London', '+0:00', 'Greenwich Mean Time'],
[184, 'Africa/Algiers', '+1:00', 'Central European Time'],
[185, 'Africa/Bangui', '+1:00', 'Western African Time'],
[186, 'Africa/Brazzaville', '+1:00', 'Western African Time'],
[187, 'Africa/Ceuta', '+1:00', 'Central European Time'],
[188, 'Africa/Douala', '+1:00', 'Western African Time'],
[189, 'Africa/Kinshasa', '+1:00', 'Western African Time'],
[190, 'Africa/Lagos', '+1:00', 'Western African Time'],
[191, 'Africa/Libreville', '+1:00', 'Western African Time'],
[192, 'Africa/Luanda', '+1:00', 'Western African Time'],
[193, 'Africa/Malabo', '+1:00', 'Western African Time'],
[194, 'Africa/Ndjamena', '+1:00', 'Western African Time'],
[195, 'Africa/Niamey', '+1:00', 'Western African Time'],
[196, 'Africa/Porto-Novo', '+1:00', 'Western African Time'],
[197, 'Africa/Tunis', '+1:00', 'Central European Time'],
[198, 'Africa/Windhoek', '+1:00', 'Western African Time'],
[199, 'Arctic/Longyearbyen', '+1:00', 'Central European Time'],
[200, 'Atlantic/Jan_Mayen', '+1:00', 'Central European Time'],
[201, 'Europe/Amsterdam', '+1:00', 'Central European Time'],
[202, 'Europe/Andorra', '+1:00', 'Central European Time'],
[203, 'Europe/Belgrade', '+1:00', 'Central European Time'],
[204, 'Europe/Berlin', '+1:00', 'Central European Time'],
[205, 'Europe/Bratislava', '+1:00', 'Central European Time'],
[206, 'Europe/Brussels', '+1:00', 'Central European Time'],
[207, 'Europe/Budapest', '+1:00', 'Central European Time'],
[208, 'Europe/Copenhagen', '+1:00', 'Central European Time'],
[209, 'Europe/Gibraltar', '+1:00', 'Central European Time'],
[210, 'Europe/Ljubljana', '+1:00', 'Central European Time'],
[211, 'Europe/Luxembourg', '+1:00', 'Central European Time'],
[212, 'Europe/Madrid', '+1:00', 'Central European Time'],
[213, 'Europe/Malta', '+1:00', 'Central European Time'],
[214, 'Europe/Monaco', '+1:00', 'Central European Time'],
[215, 'Europe/Oslo', '+1:00', 'Central European Time'],
[216, 'Europe/Paris', '+1:00', 'Central European Time'],
[217, 'Europe/Podgorica', '+1:00', 'Central European Time'],
[218, 'Europe/Prague', '+1:00', 'Central European Time'],
[219, 'Europe/Rome', '+1:00', 'Central European Time'],
[220, 'Europe/San_Marino', '+1:00', 'Central European Time'],
[221, 'Europe/Sarajevo', '+1:00', 'Central European Time'],
[222, 'Europe/Skopje', '+1:00', 'Central European Time'],
[223, 'Europe/Stockholm', '+1:00', 'Central European Time'],
[224, 'Europe/Tirane', '+1:00', 'Central European Time'],
[225, 'Europe/Vaduz', '+1:00', 'Central European Time'],
[226, 'Europe/Vatican', '+1:00', 'Central European Time'],
[227, 'Europe/Vienna', '+1:00', 'Central European Time'],
[228, 'Europe/Warsaw', '+1:00', 'Central European Time'],
[229, 'Europe/Zagreb', '+1:00', 'Central European Time'],
[230, 'Europe/Zurich', '+1:00', 'Central European Time'],
[231, 'Africa/Blantyre', '+2:00', 'Central African Time'],
[232, 'Africa/Bujumbura', '+2:00', 'Central African Time'],
[233, 'Africa/Cairo', '+2:00', 'Eastern European Time'],
[234, 'Africa/Gaborone', '+2:00', 'Central African Time'],
[235, 'Africa/Harare', '+2:00', 'Central African Time'],
[236, 'Africa/Johannesburg', '+2:00', 'South Africa Standard Time'],
[237, 'Africa/Kigali', '+2:00', 'Central African Time'],
[238, 'Africa/Lubumbashi', '+2:00', 'Central African Time'],
[239, 'Africa/Lusaka', '+2:00', 'Central African Time'],
[240, 'Africa/Maputo', '+2:00', 'Central African Time'],
[241, 'Africa/Maseru', '+2:00', 'South Africa Standard Time'],
[242, 'Africa/Mbabane', '+2:00', 'South Africa Standard Time'],
[243, 'Africa/Tripoli', '+2:00', 'Eastern European Time'],
[244, 'Asia/Amman', '+2:00', 'Eastern European Time'],
[245, 'Asia/Beirut', '+2:00', 'Eastern European Time'],
[246, 'Asia/Damascus', '+2:00', 'Eastern European Time'],
[247, 'Asia/Gaza', '+2:00', 'Eastern European Time'],
[248, 'Asia/Istanbul', '+2:00', 'Eastern European Time'],
[249, 'Asia/Jerusalem', '+2:00', 'Israel Standard Time'],
[250, 'Asia/Nicosia', '+2:00', 'Eastern European Time'],
[251, 'Asia/Tel_Aviv', '+2:00', 'Israel Standard Time'],
[252, 'Europe/Athens', '+2:00', 'Eastern European Time'],
[253, 'Europe/Bucharest', '+2:00', 'Eastern European Time'],
[254, 'Europe/Chisinau', '+2:00', 'Eastern European Time'],
[255, 'Europe/Helsinki', '+2:00', 'Eastern European Time'],
[256, 'Europe/Istanbul', '+2:00', 'Eastern European Time'],
[257, 'Europe/Kaliningrad', '+2:00', 'Eastern European Time'],
[258, 'Europe/Kiev', '+2:00', 'Eastern European Time'],
[259, 'Europe/Mariehamn', '+2:00', 'Eastern European Time'],
[260, 'Europe/Minsk', '+2:00', 'Eastern European Time'],
[261, 'Europe/Nicosia', '+2:00', 'Eastern European Time'],
[262, 'Europe/Riga', '+2:00', 'Eastern European Time'],
[263, 'Europe/Simferopol', '+2:00', 'Eastern European Time'],
[264, 'Europe/Sofia', '+2:00', 'Eastern European Time'],
[265, 'Europe/Tallinn', '+2:00', 'Eastern European Time'],
[266, 'Europe/Tiraspol', '+2:00', 'Eastern European Time'],
[267, 'Europe/Uzhgorod', '+2:00', 'Eastern European Time'],
[268, 'Europe/Vilnius', '+2:00', 'Eastern European Time'],
[269, 'Europe/Zaporozhye', '+2:00', 'Eastern European Time'],
[270, 'Africa/Addis_Ababa', '+3:00', 'Eastern African Time'],
[271, 'Africa/Asmara', '+3:00', 'Eastern African Time'],
[272, 'Africa/Asmera', '+3:00', 'Eastern African Time'],
[273, 'Africa/Dar_es_Salaam', '+3:00', 'Eastern African Time'],
[274, 'Africa/Djibouti', '+3:00', 'Eastern African Time'],
[275, 'Africa/Kampala', '+3:00', 'Eastern African Time'],
[276, 'Africa/Khartoum', '+3:00', 'Eastern African Time'],
[277, 'Africa/Mogadishu', '+3:00', 'Eastern African Time'],
[278, 'Africa/Nairobi', '+3:00', 'Eastern African Time'],
[279, 'Antarctica/Syowa', '+3:00', 'Syowa Time'],
[280, 'Asia/Aden', '+3:00', 'Arabia Standard Time'],
[281, 'Asia/Baghdad', '+3:00', 'Arabia Standard Time'],
[282, 'Asia/Bahrain', '+3:00', 'Arabia Standard Time'],
[283, 'Asia/Kuwait', '+3:00', 'Arabia Standard Time'],
[284, 'Asia/Qatar', '+3:00', 'Arabia Standard Time'],
[285, 'Europe/Moscow', '+3:00', 'Moscow Standard Time'],
[286, 'Europe/Volgograd', '+3:00', 'Volgograd Time'],
[287, 'Indian/Antananarivo', '+3:00', 'Eastern African Time'],
[288, 'Indian/Comoro', '+3:00', 'Eastern African Time'],
[289, 'Indian/Mayotte', '+3:00', 'Eastern African Time'],
[290, 'Asia/Tehran', '+3:30', 'Iran Standard Time'],
[291, 'Asia/Baku', '+4:00', 'Azerbaijan Time'],
[292, 'Asia/Dubai', '+4:00', 'Gulf Standard Time'],
[293, 'Asia/Muscat', '+4:00', 'Gulf Standard Time'],
[294, 'Asia/Tbilisi', '+4:00', 'Georgia Time'],
[295, 'Asia/Yerevan', '+4:00', 'Armenia Time'],
[296, 'Europe/Samara', '+4:00', 'Samara Time'],
[297, 'Indian/Mahe', '+4:00', 'Seychelles Time'],
[298, 'Indian/Mauritius', '+4:00', 'Mauritius Time'],
[299, 'Indian/Reunion', '+4:00', 'Reunion Time'],
[300, 'Asia/Kabul', '+4:30', 'Afghanistan Time'],
[301, 'Asia/Aqtau', '+5:00', 'Aqtau Time'],
[302, 'Asia/Aqtobe', '+5:00', 'Aqtobe Time'],
[303, 'Asia/Ashgabat', '+5:00', 'Turkmenistan Time'],
[304, 'Asia/Ashkhabad', '+5:00', 'Turkmenistan Time'],
[305, 'Asia/Dushanbe', '+5:00', 'Tajikistan Time'],
[306, 'Asia/Karachi', '+5:00', 'Pakistan Time'],
[307, 'Asia/Oral', '+5:00', 'Oral Time'],
[308, 'Asia/Samarkand', '+5:00', 'Uzbekistan Time'],
[309, 'Asia/Tashkent', '+5:00', 'Uzbekistan Time'],
[310, 'Asia/Yekaterinburg', '+5:00', 'Yekaterinburg Time'],
[311, 'Indian/Kerguelen', '+5:00', 'French Southern & Antarctic Lands Time'],
[312, 'Indian/Maldives', '+5:00', 'Maldives Time'],
[313, 'Asia/Calcutta', '+5:30', 'India Standard Time'],
[314, 'Asia/Colombo', '+5:30', 'India Standard Time'],
[315, 'Asia/Kolkata', '+5:30', 'India Standard Time'],
[316, 'Asia/Katmandu', '+5:45', 'Nepal Time'],
[317, 'Antarctica/Mawson', '+6:00', 'Mawson Time'],
[318, 'Antarctica/Vostok', '+6:00', 'Vostok Time'],
[319, 'Asia/Almaty', '+6:00', 'Alma-Ata Time'],
[320, 'Asia/Bishkek', '+6:00', 'Kirgizstan Time'],
[321, 'Asia/Dacca', '+6:00', 'Bangladesh Time'],
[322, 'Asia/Dhaka', '+6:00', 'Bangladesh Time'],
[323, 'Asia/Novosibirsk', '+6:00', 'Novosibirsk Time'],
[324, 'Asia/Omsk', '+6:00', 'Omsk Time'],
[325, 'Asia/Qyzylorda', '+6:00', 'Qyzylorda Time'],
[326, 'Asia/Thimbu', '+6:00', 'Bhutan Time'],
[327, 'Asia/Thimphu', '+6:00', 'Bhutan Time'],
[328, 'Indian/Chagos', '+6:00', 'Indian Ocean Territory Time'],
[329, 'Asia/Rangoon', '+6:30', 'Myanmar Time'],
[330, 'Indian/Cocos', '+6:30', 'Cocos Islands Time'],
[331, 'Antarctica/Davis', '+7:00', 'Davis Time'],
[332, 'Asia/Bangkok', '+7:00', 'Indochina Time'],
[333, 'Asia/Ho_Chi_Minh', '+7:00', 'Indochina Time'],
[334, 'Asia/Hovd', '+7:00', 'Hovd Time'],
[335, 'Asia/Jakarta', '+7:00', 'West Indonesia Time'],
[336, 'Asia/Krasnoyarsk', '+7:00', 'Krasnoyarsk Time'],
[337, 'Asia/Phnom_Penh', '+7:00', 'Indochina Time'],
[338, 'Asia/Pontianak', '+7:00', 'West Indonesia Time'],
[339, 'Asia/Saigon', '+7:00', 'Indochina Time'],
[340, 'Asia/Vientiane', '+7:00', 'Indochina Time'],
[341, 'Indian/Christmas', '+7:00', 'Christmas Island Time'],
[342, 'Antarctica/Casey', '+8:00', 'Western Standard Time (Australia)'],
[343, 'Asia/Brunei', '+8:00', 'Brunei Time'],
[344, 'Asia/Choibalsan', '+8:00', 'Choibalsan Time'],
[345, 'Asia/Chongqing', '+8:00', 'China Standard Time'],
[346, 'Asia/Chungking', '+8:00', 'China Standard Time'],
[347, 'Asia/Harbin', '+8:00', 'China Standard Time'],
[348, 'Asia/Hong_Kong', '+8:00', 'Hong Kong Time'],
[349, 'Asia/Irkutsk', '+8:00', 'Irkutsk Time'],
[350, 'Asia/Kashgar', '+8:00', 'China Standard Time'],
[351, 'Asia/Kuala_Lumpur', '+8:00', 'Malaysia Time'],
[352, 'Asia/Kuching', '+8:00', 'Malaysia Time'],
[353, 'Asia/Macao', '+8:00', 'China Standard Time'],
[354, 'Asia/Macau', '+8:00', 'China Standard Time'],
[355, 'Asia/Makassar', '+8:00', 'Central Indonesia Time'],
[356, 'Asia/Manila', '+8:00', 'Philippines Time'],
[357, 'Asia/Shanghai', '+8:00', 'China Standard Time'],
[358, 'Asia/Singapore', '+8:00', 'Singapore Time'],
[359, 'Asia/Taipei', '+8:00', 'China Standard Time'],
[360, 'Asia/Ujung_Pandang', '+8:00', 'Central Indonesia Time'],
[361, 'Asia/Ulaanbaatar', '+8:00', 'Ulaanbaatar Time'],
[362, 'Asia/Ulan_Bator', '+8:00', 'Ulaanbaatar Time'],
[363, 'Asia/Urumqi', '+8:00', 'China Standard Time'],
[364, 'Australia/Perth', '+8:00', 'Western Standard Time (Australia)'],
[365, 'Australia/West', '+8:00', 'Western Standard Time (Australia)'],
[366, 'Australia/Eucla', '+8:45', 'Central Western Standard Time (Australia)'],
[367, 'Asia/Dili', '+9:00', 'Timor-Leste Time'],
[368, 'Asia/Jayapura', '+9:00', 'East Indonesia Time'],
[369, 'Asia/Pyongyang', '+9:00', 'Korea Standard Time'],
[370, 'Asia/Seoul', '+9:00', 'Korea Standard Time'],
[371, 'Asia/Tokyo', '+9:00', 'Japan Standard Time'],
[372, 'Asia/Yakutsk', '+9:00', 'Yakutsk Time'],
[373, 'Australia/Adelaide', '+9:30', 'Central Standard Time (South Australia)'],
[374, 'Australia/Broken_Hill', '+9:30', 'Central Standard Time (South Australia/New South Wales)'],
[375, 'Australia/Darwin', '+9:30', 'Central Standard Time (Northern Territory)'],
[376, 'Australia/North', '+9:30', 'Central Standard Time (Northern Territory)'],
[377, 'Australia/South', '+9:30', 'Central Standard Time (South Australia)'],
[378, 'Australia/Yancowinna', '+9:30', 'Central Standard Time (South Australia/New South Wales)'],
[379, 'Antarctica/DumontDUrville', '+10:00', 'Urville Time(Dumont)'],
[380, 'Asia/Sakhalin', '+10:00', 'Sakhalin Time'],
[381, 'Asia/Vladivostok', '+10:00', 'Vladivostok Time'],
[382, 'Australia/ACT', '+10:00', 'Eastern Standard Time (New South Wales)'],
[383, 'Australia/Brisbane', '+10:00', 'Eastern Standard Time (Queensland)'],
[384, 'Australia/Canberra', '+10:00', 'Eastern Standard Time (New South Wales)'],
[385, 'Australia/Currie', '+10:00', 'Eastern Standard Time (New South Wales)'],
[386, 'Australia/Hobart', '+10:00', 'Eastern Standard Time (Tasmania)'],
[387, 'Australia/Lindeman', '+10:00', 'Eastern Standard Time (Queensland)'],
[388, 'Australia/Melbourne', '+10:00', 'Eastern Standard Time (Victoria)'],
[389, 'Australia/NSW', '+10:00', 'Eastern Standard Time (New South Wales)'],
[390, 'Australia/Queensland', '+10:00', 'Eastern Standard Time (Queensland)'],
[391, 'Australia/Sydney', '+10:00', 'Eastern Standard Time (New South Wales)'],
[392, 'Australia/Tasmania', '+10:00', 'Eastern Standard Time (Tasmania)'],
[393, 'Australia/Victoria', '+10:00', 'Eastern Standard Time (Victoria)'],
[394, 'Australia/LHI', '+10:30', 'Lord Howe Standard Time'],
[395, 'Australia/Lord_Howe', '+10:30', 'Lord Howe Standard Time'],
[396, 'Asia/Magadan', '+11:00', 'Magadan Time'],
[397, 'Antarctica/McMurdo', '+12:00', 'New Zealand Standard Time'],
[398, 'Antarctica/South_Pole', '+12:00', 'New Zealand Standard Time'],
[399, 'Asia/Anadyr', '+12:00', 'Anadyr Time'],
[400, 'Asia/Kamchatka', '+12:00', 'Petropavlovsk-Kamchatski Time'],
];
